### ISSUE TITLE
Undefined property: stdClass::$traits

### ISSUE THREAD

**Issue by since1976** [lukeholder/craft-geo#2]
Have this running on a local MAMP install and get the above internal server error when setting dev mode to false.

**Comment by since1976** [comment]
Works perfectly thanks Luke.

**Comment by johanneslamers** [comment]
Hi @lukeholder I have the same issue. Running on an local MAMP. Dev mode is on. geo.php config is set up with my outgoing ip. Still the same error. Even if I enter the IP in config.php (in you geo plugin folder) I get the same error.

**Comment by johanneslamers** [comment]
Turns out... some IP addresses in the Netherlands work and some don't.

Works: 62.163.41.14
My IP: 92.111.6.18 don't work. 

Can you make some sort of condition if it fails to lookup the ip no PHP error gets in the way?

**Comment by lukeholder** [comment]
Updated to check for existence of region and state first. return blank string if no data is returned from API. see release for version 1.3. Thanks for reporting. A more robust fallback for geo will be in version 2.

1.3 can be downloaded here: https://github.com/lukeholder/craft-geo/releases/tag/1.3

**Comment by timeverts** [comment]
Hi @lukeholder. This is a very useful little plugin. However, I have recently installed this plugin on a client's site and have seen 2 of these particular errors reported so far. 

The latest was with the following setup:
- Craft CMS: 2.6.2966
- Client IP: 123.176.115.8
- Browser: IE 11.0
- OS: Windows 10

**Comment by cliveportman** [comment]
I'm getting this error also, but only on two iPhones using the same mobile network in the UK. Another iPhone on a different network and an Android device on a third network work fine.

Bizarrely, the JSON looks fine - here's one that doesn't work, returning everything as I'd expect: http://geoip.nekudo.com/api/82.132.243.85/full
