### ISSUE TITLE
Using paid account for Telize

### ISSUE THREAD

**Issue by zizther** [lukeholder/craft-geo#3]
Hi.

Does this plugin still use Telize's free account, as this was closed in Nov 2015.
Does the plugin allow you to work with its paid plans?

Thanks

**Comment by zizther** [comment]
Hi Luke.

Any updates on this?

**Comment by lukeholder** [comment]
Hi @zizther sorry I missed your previous message. I will look into it and let you know.

**Comment by zizther** [comment]
No worries.
It seems that it is just being offered as a open source project now.

I was going to swap out Telize for another service, such as ipinfo.io and maybe another as a fallback.
I will have a look and see what else is around.
I don't know what ideas you had for this plugin, I don't want to make a pull request if it doesn't align with your vision for it.

**Comment by lukeholder** [comment]
I will be adding the ability to use any 3rd party geo ip locator api. Will then welcome contributions!

**Comment by lukeholder** [comment]
No longer maintained. Will not be upgraded for Craft 3.

Craft 3 alternatives include:

    https://plugins.craftcms.com/geo-cookie
    https://plugins.craftcms.com/geomate
    https://plugins.craftcms.com/country-detect
