### ISSUE TITLE
Undefined offset: 3 /craft/plugins/geo/services/Geo_LocationService.php:136)

### ISSUE THREAD

**Issue by schellenbergk** [lukeholder/craft-geo#7]
Undefined offset: 3 /craft/plugins/geo/services/Geo_LocationService.php:136

```private function anonymizeIp($ip) {
        if (filter_var($ip, FILTER_VALIDATE_IP) !== false) {
            $segments = explode('.', $ip);
```

Parameter `FILTER_VALIDATE_IP` validates both `ipv4` and `ipv6` addresses.  `ipv6` addresses cause undefined offset as it does not have any periods.

**Comment by lukeholder** [comment]
No longer maintained. Will not be upgraded for Craft 3.

Craft 3 alternatives include:

    https://plugins.craftcms.com/geo-cookie
    https://plugins.craftcms.com/geomate
    https://plugins.craftcms.com/country-detect
