### ISSUE TITLE
Nekudo API discontinued

### ISSUE THREAD

**Issue by ffauvel** [lukeholder/craft-geo#8]
Nekudo is now IPAPI. You now need an API Key to use their service and the limit of request for free is at 10000 per month.
https://github.com/nekudocom/shiny_geoip/blob/master/README.md#readme

**Comment by adamhopkinson** [comment]
We're also seeing this problem. @lukeholder any plans for a patch?

**Comment by adamhopkinson** [comment]
I've created a pull request to fix this.

Three things to note:

- I took out the `subdivisions` property as I couldn't see a corresponding property in the IPAPI response (and I'm not using it myself, so...)
- You need to sign up for IPAPI, which is free (see the next point), and add your api key to `config/geo.php`
- The webservice is called over http, but redirects to https - which is only enabled on paid accounts. So for now, you may have to pay.

Also, I don't often submit pull requests to other projects and had to do this completely in-browser - so apologies if I've done anything incorrectly!

**Comment by cavellblood** [comment]
I've created a pull request is in effort to close this issue.

- Updated the geo ip lookup service to use ipapi.com since the Nekudo Geo IP is now discontinued.
- I've also added a control panel settings page mainly because I thought it best to add API keys via the control panel rather than in a config.php file that could be committed to a repo. The option still exists to set the `ipApiKey` via a config file but it doesn't have to be set there for the plugin to work correctly.
- I also removed the example code and added/updated it to the readme.md.

Version 1.5.3 is working well in production environments.

**Comment by lukeholder** [comment]
@cavellblood @adamhopkinson are both your PR compatible with each other?

**Comment by cavellblood** [comment]
@lukeholder I believe they both do the same thing but we've both edited some of the same areas of code. I'll look at what @adamhopkinson has in his PR and see how it compares to my PR.

**Comment by cavellblood** [comment]
@lukeholder In my PR I did remove the `config.php` file and defined the settings with the `defineSettings` function of the plugin. @adamhopkinson used the existing `config.php` file as you had there before. So we are fetching the `ipApiKey` differently but other than they changes look mostly the same.

**Comment by adamhopkinson** [comment]
@lukeholder mine was a quick fix; @cavellblood did a _far_ more comprehensive job! So I'd disregard mine and take his.

**Comment by outline4** [comment]
@cavellblood thanks a lot! 

It did work like a charm. 
I had trouble finding the correct download link, so I am posting it here:   
[https://github.com/cavellblood/craft-geo](https://github.com/cavellblood/craft-geo)

**Comment by proimage** [comment]
Is this Craft 3-compatible?

**Comment by cavellblood** [comment]
@proimage This plugin is for Craft 2.x. But it could be ported to Craft 3.

**Comment by lukeholder** [comment]
No longer maintained. Will not be upgraded for Craft 3.

Craft 3 alternatives include:

    https://plugins.craftcms.com/geo-cookie
    https://plugins.craftcms.com/geomate
    https://plugins.craftcms.com/country-detect
